name: dino_runner
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  shared_preferences: 2.0.15
  google_mobile_ads: 1.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: 0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

flutter: 
  assets: 
    - assets/images/
    - assets/images/dino/
    - assets/images/cacti/
    - assets/images/ptera/
  uses-material-design: true

